== Development progress

* optimisation models (TODO)
** not started
* weibull estimation
** 2p complete
*** [.line-through]#rank regression (NA)#
*** [.line-through]#MLE#
**** [.line-through]#graph#
**** [.line-through]#confidence interval (hessian, 1 and 2 side)#
** [.line-through]#2p censored#
*** [.line-through]#rank regression#
**** [.line-through]#graph#
**** [.line-through]#confidence interval (median rank)#
*** [.line-through]#MLE#
**** [.line-through]#graph#
**** [.line-through]#confidence interval (hessian, 1 and 2 side)#
** auto selection of fit method

//TODO
** 3p complete
*** [.line-through]#rank regression#.
*** MLE (todo)


== Description

Utilisation of information collected by CMMS (computerised maintenance management systems) for improving
a maintenance policy is a long-standing problem. In many organisations failure and cost data from their asset is not
used at all. This tool will automatically choose most suitable maintenance policy by solving optimisation problems.

=== Optimization problems
//TODO
* Component replacement interval
* Inspection interval
* Capital equipment replacement interval
* Maintenance resource requirements

==== Parameters:

* *Cost*.
** Maintenance cost
** Operation cost
** Replacement cost
* *Failure rate*. WEMIOT has its own module for evaluation parameters of Weibull distribution based on failure information
from CMMS.

==== Constraints

* *Avialability*
* *Safety*
* other

== References
1. Labib, Ashraf W. "A decision analysis model for maintenance policy selection using a CMMS." Journal of Quality in
Maintenance Engineering (2004).
2. Jardine, Andrew KS, and Albert HC Tsang. Maintenance, replacement, and reliability: theory and applications.
CRC press, 2013.
3. Aggarwal, Charu C. Linear Algebra and Optimization for Machine Learning: A Textbook. Springer Nature, 2020.