== Development progress

* optimisation models (TODO)
* weibull estimation
** 2p complete
*** rank regression (done)
**** graph (done)
**** confidence interval (median rank) (done)
*** MLE
**** graph (done)
**** confidence interval (hessian, 1 and 2 side)
** 2p censored
*** rank regression (done)
**** graph (done)
**** confidence interval (median rank) (done)
*** MLE
**** graph (done)
**** confidence interval (hessian, 1 and 2 side)
** 3p complete
*** rank regression. (todo)
*** MLE (todo)


== Description

Utilisation of information collected by CMMS (computerised maintenance management systems) for improving
a maintenance policy is a long-standing problem. In many organisations failure and cost data from their asset is not
used at all. This tool will automatically choose most suitable maintenance policy by solving optimisation problems.

=== Optimization problems

* Component replacement interval
* Inspection interval
* Capital equipment replacement interval
* Maintenance resource requirements

==== Parameters:

* *Cost*.
** Maintenance cost
** Operation cost
** Replacement cost
* *Failure rate*. WEMIOT has its own module for evaluation parameters of Weibull distribution based on failure information
from CMMS.

==== Constraints

* *Avialability*
* *Safety*
* other

== References
1. Labib, Ashraf W. "A decision analysis model for maintenance policy selection using a CMMS." Journal of Quality in
Maintenance Engineering (2004).
2. Jardine, Andrew KS, and Albert HC Tsang. Maintenance, replacement, and reliability: theory and applications.
CRC press, 2013.
3. Aggarwal, Charu C. Linear Algebra and Optimization for Machine Learning: A Textbook. Springer Nature, 2020.